algoritmo "Exercício 1 - Algoritmos - Fixação"
var
A,B,C: inteiro

inicio
//Armazenado os valores de A e B usando atribuição de variáveis.
Escreval("Atribuindo valores para A e B usando atribuição de variáveis.")
A <- 10
B <- 20
C <- 10
Escreval("A=", A)
Escreval("B=", B)
//Fazendo a troca de valores entre A e B utilizando apenas atribuição de variáveis.
Escreval("Troca de valores entre A e B")
A <- 20
C <- 10
B <- C
Escreval("A=", A)
Escreval("B=", B)
fimalgoritmo